### ISSUE TITLE
Least Priviledge Deployment for Kubernetes

### ISSUE THREAD

**Issue by seafoodbuffet** [aerokube/moon-deploy#109]
The default deployment essentially requires clusterwide super-user. Is there a more restrictive set of permissions that might be possible here? Also, what if our kube cluster has restricted container registry sources, what source(s) do we need to add in order for moon to work?

**Comment by vania-pooh** [comment]
@seafoodbuffet take a look at the following:

1) Permissions: https://github.com/aerokube/moon-deploy/blob/master/moon-local.yaml#L12-L46 Meanwhile will add the same permissions to `moon.yaml`.
2) Custom registry: https://aerokube.com/moon/latest/#_using_custom_docker_registry
