### ISSUE TITLE
Migrate from Ingress extensions/v1beta1 to avoid being broken in 1.22

### ISSUE THREAD

**Issue by alexgallax** [aerokube/moon-deploy#128]
According to https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

"The v1.22 release will stop serving the following deprecated API versions in favor of newer and more stable API versions:

Ingress in the extensions/v1beta1 API version will no longer be served
Migrate to use the networking.k8s.io/v1beta1 API version, available since v1.14. Existing persisted data can be retrieved/updated via the new version."

Now **"helm/templates/ingress.yml"** has **"apiVersion: extensions/v1beta1"** that will break deployment in the future **v1.22**. Just to help you to keep it in view.

**Comment by vania-pooh** [comment]
@alexgallax this Helm chart is deprecated and will be removed soon. An up to date Helm is here: https://github.com/aerokube/charts

**Comment by alexgallax** [comment]
Got it, thanks.

**Comment by vania-pooh** [comment]
Closing then.
