### ISSUE TITLE
Provide a helm repository for moon

### ISSUE THREAD

**Issue by benzman81** [aerokube/moon-deploy#42]
Would be great if you provide a helm repository for moon.

Currently we have to checkout moon deploy, create a helm tgz and deploy it to our private repository.

**Comment by vania-pooh** [comment]
Need to host tarballs in separate branch and use GH-pages to host them. https://helm.sh/docs/chart_repository/

**Comment by vania-pooh** [comment]
Example repository. https://github.com/technosophos/tscharts/tree/master/docs

**Comment by vania-pooh** [comment]
Done. Moved to a separate repository. https://github.com/aerokube/charts
