### ISSUE TITLE
htpasswd needs to be base64 in helm chart

### ISSUE THREAD

**Issue by benzman81** [aerokube/moon-deploy#45]
Today, if you set htpasswd via values.yaml, you need to convert the value to base64.
To fix this and make it easier using the helm-chart you can use the following:

`users.htpasswd: {{ .Values.htpasswd | b64enc | quote }}`

This way, the user does not need to encode it as helm does it for you.
Same for license key.

**Comment by vania-pooh** [comment]
@benzman81 PRs are welcome. :)

**Comment by vania-pooh** [comment]
Fixed in #47
