### ISSUE TITLE
upload to s3 via iam role

### ISSUE THREAD

**Issue by ofirshtrull** [aerokube/moon-deploy#67]
I am running moon on aws(eks)
i have added 
```apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: moon
data:
  service.json: |
    {
      "s3": {
        "endpoint": "https://s3-eu-west-1.amazonaws.com",
        "bucketName": "my-moon-videos",
        "version": "S3v2"
      },
      "images": {
        "videoRecorder": "aerokube/moon-video-recorder:latest-release",
        "defender": "aerokube/defender:latest-release",
        "logger": "aerokube/logger:latest-release"
      }
    }
```

and no matter what I change if I access the logs 
`k logs -f pod/moon-86b77d86d8-nxpvt moon`
I get [INIT] [S3 upload is disabled: no S3 endpoint specified]

How do i enable the S3 upload

**Comment by aandryashin** [comment]
For now authentication via iam role does not implemented, you have to set
access key and secret key to enable S3 upload.

чт, 20 февр. 2020 г., 18:03 ofir shtrull <notifications@github.com>:

**Comment by ofirshtrull** [comment]
can we add a feature flag for this?

**Comment by aandryashin** [comment]
We are planning to implement that feature in further release...

чт, 20 февр. 2020 г., 18:15 ofir shtrull <notifications@github.com>:

**Comment by ofirshtrull** [comment]
and even when i add the 
```
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: moon
stringData:
  s3.accessKey: "aaaaaaa"
  s3.secretKey: "vbbbbbbb"
```
is still wont work

**Comment by vania-pooh** [comment]
@ofirshtrull you have to uncomment [this](https://github.com/aerokube/moon-deploy/blob/master/moon.yaml#L120-L125) and [this](https://github.com/aerokube/moon-deploy/blob/master/moon.yaml#L162-L167) to mount secret \ config map to Moon pod.

**Comment by ofirshtrull** [comment]
Thanks
