### ISSUE TITLE
Chart 1.6.0 - "" missing in port definition for Safari

### ISSUE THREAD

**Issue by marcinbojko** [aerokube/moon-deploy#93]
Missing "" - https://github.com/aerokube/moon-deploy/blob/8e6cf7a1c0be16bed878c54ec14afcd03915df1a/chart/moon/values.yaml#L229

causes to fail loading browsers definition as a port for Safari browsers is not double-quoted.

**Comment by vania-pooh** [comment]
Fixed in #95.
